# Generated by Django 5.1.6 on 2025-02-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepmart', '0002_advertisement_delete_trendimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
